apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification
  name: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  strategy: {}
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - image: onikaze/sample-app-k8s-notification:16
        name: notification
        envFrom:
        - secretRef:
            name: smtp-info
        volumeMounts:
          - name: app-storage
            mountPath: /app/log
            subPath: log
          - name: app-storage
            mountPath: /app/db
            subPath: db
        resources:
          requests:
            cpu: 1
            memory: 500m
          limits:
            cpu: 1
            memory: 500m
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-notification-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5003
  selector:
    app: notification
