apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  strategy: {}
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: onikaze/sample-app-k8s-user:16
        name: user
        volumeMounts:
          - name: app-storage
            mountPath: /app/log
            subPath: log
          - name: app-storage
            mountPath: /app/db
            subPath: db
        resources:
          requests:
            cpu: 1
            memory: 500m
          limits:
            cpu: 1
            memory: 500m
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-user-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: user

