apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-user-pv
  labels:
    name: app-user-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e91fe7c6cec79569
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-user-pvc
  namespace: app
  annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: app-user-pv
  storageClassName: efs-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-post-pv
  labels:
    name: app-post-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e91fe7c6cec79569
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-post-pvc
  namespace: app
  annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: app-post-pv
  storageClassName: efs-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-notification-pv
  labels:
    name: app-notification-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e91fe7c6cec79569
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-notification-pvc
  namespace: app
  annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: app-notification-pv
  storageClassName: efs-sc
